language: scala
scala:
- 2.11.12
- 2.12.4
jdk:
- oraclejdk8
branches:
  only:
  - master
before_script:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi
script:
- |
  if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ "$TRAVIS_BRANCH" = "master" ] && [[ $(cat version.sbt) =~ "-SNAPSHOT" ]]; then
    openssl aes-256-cbc -k "$ENCRYPTION_PASSWORD" -in secrets.tar.enc -out secrets.tar -d
    tar xvf secrets.tar
    sbt ++$TRAVIS_SCALA_VERSION clean compile coverage test coverageReport publishSigned
  else
    sbt ++$TRAVIS_SCALA_VERSION clean compile coverage test coverageReport
  fi
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
after_success:
- bash <(curl -s https://codecov.io/bash)
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION"
env:
  global:
  - secure: makKxQYXanKpnuvz/7cj852llD6A0bK3hEabhb/JHmOOMBF0sbiuuehftNLYGIg4wjSKC81kbsQF75UqlxbbG3NpOkJsYJ4sHbtUDAb2X8FERYsvw+M51/3mGroCiKh2bL7rpGE0rUIO5jDdqSu7RECHmpPpltkWlDaFTHq4G1aHRc2HdaFzOv+YfG8zUC4R1mD7hrKSWTDV4lTm13m0SRWJOXTHo6EHqEK5uEViXBR75ec+gyvO4pgiss0zaNWQVoB8HgrTw5mOkj9yWXNJ9+XSVZd0VeJ9wwtAjoSnnMiKeorNsKtG8ZBTo4nfREhkwEvl0mEPYKKnLoLV9hFlgR46awx0UuGiQw4aXyiWd6GMizabRaPaTiP0yhGyuTGYqpXxQXWRc5B1CxJWd2KY2OF5DaTxeXn1iUB7nERJRLILdtuRqI7WDVekA96AspUg+ck1jrrB+xhhXoxyNDjMcpnIaBhRMbrEcurQejhmFlK2wDfkUiM6fqJ8xLv3n01KDQf+oVOw0/L2Ej7m0oakwg1KiHmAY0aCILwxilaI3A1NCXfNtXX85SppNZJ+yHXRl3nqMitrwoxRKhwtxSTsDSKErNjsz44ZJgHbZnL1EUsPflnlX7tnb963Za9NhvFQPDcdZ1IzusSrWrEESdHr6PrNfnnZaKDckC5fPIaDLxI=
  - secure: IZ8IJ5vwIdTxjEcTlTZMhtMA455CCHuTLEm4NcvfHtOr/2fm+2/taHyjUPDDk5ZC0GLcYmhMZ6YC2B2g6aUrQKbLy4oH8nBSfypJuzU4nsTqQry3P/Gn4+ib6za4NqlUeT8jh5E1mb9XuPt5Vk+0xtCyF229uriwzJ7i7wifU7mm3p8eeSnC/SdDKdRO58jcAfqPMjvdlo+g4dBtvMTIjTPsWJ6suw4RbOljAmd3F1sTA6kCOqESPM4VCZd4keEFWCl8Afs/4rvEwUniCFlYx+PT+Fusxijp8oDSjlKtM0UCaUjDr6/xINgRPzJbQAMd+V23B67FIVA/ERR7jWqhXFpXuubVwViEVA2nhJLU4P5QqM7nfU5nB8Q9apVl9roN0srirMfG5xC6Bw6NgiOWY9y9mJ1BoHmEA4aQISBBP47Z/vT/+34zahQF+Bs12KHBM0tIdowT4t+uIoYYieUbAbz6R0b5LABFqd8xDli8RaA51V+OrLwLgiIwga/yQ9etczyrAGX830hKQX3S3DQDiH8fSkJnYWU+4vvUSb9dBLOjUk89ei02bRviSrTo74hsI0cXo8qT4iZrQxnePg8qV3ETiVCqtjYW4sw9Z8w8Wz0CrvCtEyKHaHk4UGGRiwnbJvzpv31TRp3D+79/FFKV50fu8pFUoYkRZnfrarBDBnA=
  - secure: BIGko6H3jmJATCu4H1d0POTpFknil1qN16xbuNFV3jAhtB1fLpIvOuJnBHSkxn2zae5vLN9zUQNmwpz3i04s/yptXz6TfqhFLLzwcSJL85dhhmxd0W0cYsR4bB8hMqjgU/vNvU7lvkvGrZRxw/cGcy30H8RPbnEhbkCx+wS1PZtRqK/MyNOL9XOuMpp1YG5ArBcA2tgv+TQ4NWUydO6hQXBD6kcE4uE9GCXAIAPun2P9DqM+ie2Mi8CYkWNIWXE/g+im1pNQTHj4YxmPOo/VoDGNGg3evkXBc9pOrAPAHJEo+I7qu+GyDyzB6i5ySV1lI5625NHRPGbM9QvE0PwsTwEfPt1iGMqfKliO44jATfkIfN/3Uv01chclUZiDwhhJLxgNY6VTYHiQZG6qwL36usRRgxofQTyZSFuDPqHRC+ts40bk4R3Cxpz31cwzlJMxsfBnRFdxVYsvHd8FhoSY+9u0qtwIRzmlWjdI4QcmbbLHw9XlTrZ9LrjkmAuRk03yTK5SwpDghvW9fqiwgTQva3BjCpGjqd9RJrFfKw81Zrh4Qc25OHqcAdt7TypRlegkk/GAkqDwBR+nBJ+uEzqcuNuvVtyfvArFklCAocY4miKHwUFNeT7YO6IApxSL0fPUw1SoYNCKMOKJssNKsvXL9OvzETJyncEtSF34MC2owMc=
